#整合Activit
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  activiti:
    check-process-definitions: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    testWhileIdle: true
  security:
    user:
      name: admin
      password: 123456